### ISSUE TITLE
Can you help me to make it work?

### ISSUE THREAD

**Issue by edjalmobf** [dtroncy/docker-rpi-subliminal#2]
I'm new in subliminal (and docker too). I tried to install subliminal via official docker container, but without success, and after found you. I try download a subtitles this way:

I do this `/var/media/Seagate Backup Plus/Kodi/Filmes/Creed (2015) # docker run - -rm --name subliminal -v subliminal_cache:/usr/src/cache -it dtroncy/rpi-subliminal download -l en Creed\ \(2015\)\ Bluray-1080p.mkv `
And it show this
```
Collecting videos  [####################################]  100%  Creed (2015) BlCollecting videos  [####################################]  100%                               
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Creed (2015Downloading subtitles  [####################################]  100%                               
Some providers have been discarded due to unexpected errors: opensubtitles, legendastv
Downloaded 1 subtitle
```
but no subtitles appeared in the folder. Where is download? And how can I make it download to the same folder?

I did not login in any provider. How can I do this too?

**Comment by edjalmobf** [comment]
I got it!

The only thing I could not do is login. Look how I'm doing:
`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media/Seagate\ Backup\ Plus/Kodi:/var/media/Seagate\ Backup\ Plus/Kodi/ -it dtroncy/rpi-subliminal --legendastv username password download -l pt-BR -p legendastv -a 1w /var/media/Seagate\ Backup\ Plus/Kodi/`

And show `Some providers have been discarded due to unexpected errors: legendastv`

The same in opensubtitles.

**Comment by dtroncy** [comment]
Hi edjalmobf,

you were too fast for me:). Indeed, mount volume was missing so that the subtitle could be downloaded on the host.

For other error, I think you command is ok and I just tested at home but I obtained the same message. After switching to debug mode, I could see the following error:

SSLError:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

I'll look into the cause of this and come back to you as soon as I have more information.

**Comment by edjalmobf** [comment]
Thanks man!
I'll wait!
I working with @ratoaq2 too (like referenced before). Maybe he help us too!

**Comment by edjalmobf** [comment]
@ratoaq2 read the debug logs and said that

> Opensubtitles error is related to SSL (https connection), most likely the docker image has no certificates at all, and can't validate any SSL connections.
> The legendastv is because `unrar` is not installed in the docker image as well.
>
> So maybe, you could reach the image creator and ask about those 2

Can you fix and add this?

**Comment by dtroncy** [comment]
Hi @edjalmobf ,

I update python version for Opensubtitles problem (I think it's a python version problem and not a certificate problem) and add unrar for legendastv problem.

Can you update your image to "latest" tag and try again ?

**Comment by edjalmobf** [comment]
Opensubtitles worked great but legendastv don't
See debug: https://pastebin.com/GRJ57XHq
Look the container. I did something wrong?
![captura de tela 2019-02-25 as 15 18 17](https://user-images.githubusercontent.com/42322017/53359031-9b57e700-3910-11e9-8db5-733868cb3fe2.png)

**Comment by dtroncy** [comment]
Good news for Opensubtitles and for legendastv because error is different now.

You didn't make any mistake, I think there is another isssue.

I'll have a look at it and come back to you soon.

**Comment by edjalmobf** [comment]
Hey, you fixed! This doesn't work before because had a cache of previous version. I cleaned it (thanks @ratoaq2)(`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media -it dtroncy/rpi-subliminal cache --clear-subliminal`) and now worked :)
Thanks you and @ratoaq2 very much for this!!! :)

**Comment by dtroncy** [comment]
Good news !
