### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by edjalmobf** [dtroncy/docker-rpi-subliminal#3]
Hello, @dtroncy!
A new version of Subliminal is available, can you please update?

**Comment by dtroncy** [comment]
Hi @edjalmobf,

thanks you for the information. I will update this asap.

**Comment by dtroncy** [comment]
@edjalmobf, I just update to version 2.1.0.

**Comment by edjalmobf** [comment]
Many thanks @dtroncy :)
